---
title: "Converting Motif Formats for TOBIAS Footprinting"
author: "Suffian Azizan"
output: github_document
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load libraries
library(universalmotif)
library(tools)
```

## Load up metadata for the motifs
First, the metadata file containing the motif details are loaded.

```{r read-in-data, eval=FALSE, include=TRUE}
# Load the TSV file as a dataframe
metadata_df <- read.delim("~/Documents/local-storage/bioinf/repos/reference-TF-motifs/cisbpDB/TF_Information_all_motifs_plus_Source-Type_cols_filtered.tsv", sep = "\t") # nolint: line_length_linter.

# Print the first 6 rows of the dataframe
head(metadata_df)

```


## Use the package `universalmotif` to convert the motif files

Then, let us convert the cisBP matrix format (PWM) into `jaspar` format. 

```{r read-in-data-jaspar, eval=FALSE, include=TRUE}
# initialize counter
count <- 0
# loop through all the motif files in a folder
for (file in list.files("pwms_all_motifs/")) {
  # read in the motif
  motif <- read_cisbp(paste0("pwms_all_motifs/", file))

  # write to file as jaspar format in a tmp file
  write_jaspar(motif, "jaspar.tmp", overwrite = TRUE)

  # read in the basename of the motif file without file extension
  motif_id <- file_path_sans_ext(file)

  # filter the metadata dataframe to get the TF name; first filter by motif ID, then filter by TF status of 'direct (D)'
  filtered_metadata_df <- subset(metadata_df, Motif_ID == motif_id & TF_Status == "D" & (Motif_Type == "ChIP-seq" | Motif_Type == "ChIP-chip" | Motif_Type == "ChIP-seq+ChIP-exo")) # nolint: line_length_linter.

  # check if the filtered dataframe is empty
  if (nrow(filtered_metadata_df) == 0) {
  print("No motif found")
  next
  } else {
    if (length(unique(filtered_metadata_df$TF_Name)) == 1) {
      print("Found the associated TF. Assigning the TF name to the motif...")
      tf_name <- unique(filtered_metadata_df$TF_Name)
      motif_name <- paste0(motif_id, "\t", tf_name)
    } else {
      print("More than one TF associated with the motif are found in the database. Skipping motif extraction...") # nolint: line_length_linter.
      next
    }
  }

  # rename the string 'new motif' in the tmp file to the motif name
  file_content <- readLines("jaspar.tmp")
  file_content <- gsub("new motif", motif_name, file_content)

  # write the file content to a new individual motif file
  writeLines(file_content, paste0("jaspar_all_motifs-D-ChIP-seq-exo-filt/", motif_id, ".jaspar"))

  motif_filename <- paste0("jaspar_all_motifs-D-ChIP-seq-exo-filt/", motif_id, ".jaspar")

  # append to fresh file if count = 0
  if (count == 0) {
    file.copy(motif_filename, "all_motifs_cisbp_D-ChIP-seq-exo-filtered.jaspar")
  } else {
    file.append("all_motifs_cisbp_D-ChIP-seq-exo-filtered.jaspar", motif_filename)
  }

  # increment the counter
  count <- count + 1

  # print the motif name to the console and the current count
  print(paste0("Motif ", motif_name, " converted. Current count: ", count))
}
```

Next, we can do the same to generate a `meme` format file.

```{r read-in-data-meme, eval=FALSE, include=TRUE, echo=FALSE}

# initialize counter
count <- 0
# loop through all the motif files in a folder
for (file in list.files("pwms_all_motifs/")) {
  # read in the motif
  motif <- read_cisbp(paste0("pwms_all_motifs/", file))

  # write to file as meme format in a tmp file
  write_meme(motif, "meme.tmp", overwrite = TRUE, version = 4)

  # read in the basename of the motif file without file extension
  motif_id <- file_path_sans_ext(file)

  # filter the metadata dataframe to get the TF name; first filter by motif ID, then filter by TF status of 'direct (D)' and then by experiment type
  filtered_metadata_df <- subset(metadata_df, Motif_ID == motif_id & TF_Status == "D" & (Motif_Type == "ChIP-seq" | Motif_Type == "ChIP-chip" | Motif_Type == "ChIP-seq+ChIP-exo")) 
  
  # check if the filtered dataframe is empty
  if (nrow(filtered_metadata_df) == 0) {
  print("No motif found")
  next
  } else {
    if (length(unique(filtered_metadata_df$TF_Name)) == 1) {
      print("Found the associated TF. Assigning the TF name to the motif...")
      tf_name <- unique(filtered_metadata_df$TF_Name)
      motif_name <- paste0(motif_id, " ", tf_name)
    } else {
      print("More than one TF associated with the motif are found in the database. Skipping motif extraction...") # nolint: line_length_linter.
      next
    }
  }

  # rename the string 'new motif' in the tmp file to the motif name
  file_content <- readLines("meme.tmp")
  file_content <- gsub("new-motif", motif_name, file_content)

  # write the file content to a new individual motif file
  writeLines(file_content, paste0("meme_all_motifs-D-ChIP-seq-exo-filt/", motif_id, ".meme"))

  motif_filename <- paste0("meme_all_motifs-D-ChIP-seq-exo-filt/", motif_id, ".meme")

  # append to fresh file if count = 0
  if (count == 0) {
    file.copy(motif_filename, "all_motifs_cisbp_D-ChIP-seq-exo-filtered.meme")
  } else {
    file.append("all_motifs_cisbp_D-ChIP-seq-exo-filtered.meme", motif_filename)
  }
  
  # increment the counter
  count <- count + 1

  # print the motif name to the console and the current count
  print(paste0("Motif ", motif_name, " converted. Current count: ", count))
}
```


Read in data from JASPAR format from JASPAR database then convert into MEME.


```{r read-in-data-jaspar, eval=FALSE, include=TRUE, echo=FALSE}
library(jsonlite)
setwd('/Users/sufyazi/Documents/local-storage/bioinf/repos/reference-TF-motifs/jasparDB/')

# initialize counter
count <- 0
# loop through all the motif files in a folder
for (file in list.files("jaspar_core_hs_nonredun_chipseq-exo-only-filt_jasp/")) {
  # read in the motif
  motif <- read_jaspar(paste0("jaspar_core_hs_nonredun_chipseq-exo-only-filt_jasp/", file))
  
  # get motif_id from file name (basename)
  # read in the basename of the motif file without file extension
  motif_id <- file_path_sans_ext(file)
  
  # write to file as meme format in a tmp file
  write_meme(motif, "meme.tmp", overwrite = TRUE, version = 4)

  # read lines in meme.tmp
  file_content <- readLines("meme.tmp")

  # write the file content to a new individual motif file
  writeLines(file_content, paste0("jaspar_core_hs_nonredun_chipseq-exo-only-filt_meme/", motif_id, ".meme"))

  motif_filename <- paste0("jaspar_core_hs_nonredun_chipseq-exo-only-filt_meme/", motif_id, ".meme")

  # append to fresh file if count = 0
  if (count == 0) {
    file.copy(motif_filename, "jaspar_core_hs_TF_nonredundant-filt-matrices_chipseq-exo.meme")
  } else {
    file.append("jaspar_core_hs_TF_nonredundant-filt-matrices_chipseq-exo.meme", motif_filename)
  }
  
  # increment the counter
  count <- count + 1

  # print the motif name to the console and the current count
  print(paste0("Motif ", motif_name, " converted. Current count: ", count))
}
```

